---
insecure_ignore_host_key: true
knownhosts_file_path: "" #if insecure_ignore_host_key is false
ssh:
  user: "root"
  password: "pass$"
  host: "127.0.0.1"
  port: 22
redis:
  host: "127.0.0.1"
  port: 6379
  ssh_block_expire_key_time: 70
  data_expire_key_time: 120
